### ISSUE TITLE
model completely white, texture missing

### ISSUE THREAD

**Issue by SushilRagoonath** [Gargaj/Foxotron#27]
one with texture is windows 10 3d viewer, also works fine in lots of other software
![Screenshot_11](https://user-images.githubusercontent.com/48589447/156162981-81711233-bede-465a-89ff-a340073095b0.png)
![Screenshot_6](https://user-images.githubusercontent.com/48589447/156162986-6a5d30bc-2c93-42b9-8fb2-a9f6673fbc49.png)
[Floor1.zip](https://github.com/Gargaj/Foxotron/files/8161265/Floor1.zip)

**Comment by Gargaj** [comment]
Fixed in https://github.com/Gargaj/Foxotron/commit/5adc1a21b326d36b05dfa6d935f2b190562ccaaa
