### ISSUE TITLE
glTF (.glb) file loads with materials assigned incorrectly

### ISSUE THREAD

**Issue by vurpo** [Gargaj/Foxotron#32]
I have a model in Blender with many different materials, where if I export it as FBX and load it in Foxotron, then all the materials load correctly (but of course not including all the PBR parameters), but if I export the same as GLB and load it, it looks as if the materials are randomly assigned incorrectly to different parts of the model.

The model is going into the Evoke 3D scene compo, so I won't show it publicly yet.

**Comment by Gargaj** [comment]
Can you provide a model / scene for example?

**Comment by vurpo** [comment]
Sorry, forgot about this. This is a GLB version of the entry from Evoke (the FBX version is in the second link). It looks like the below screenshot when running Foxotron in Wine on macOS (the FBX looks correct as expected).

https://cloud.vurpo.fi/s/Wpoz8nTTBLSqbaK
https://files.scene.org/view/parties/2024/evoke24/3d_scene/raccoonviolet-oh_no.zip

![Screenshot 2024-09-22 at 4 00 24](https://github.com/user-attachments/assets/7890a8a2-bfd4-44db-ab23-f5fb18a5167d)

**Comment by Gargaj** [comment]
My bad :( https://github.com/Gargaj/Foxotron/commit/df7175dd3aa717800528bdd6802502c0426ebfc1

**Comment by Gargaj** [comment]
Now with fixed release: https://github.com/Gargaj/Foxotron/releases/tag/2024-09-23

**Comment by vurpo** [comment]
Thank you!
